### ISSUE TITLE
onDrop does not fire for same filename with different content

### ISSUE THREAD

**Issue by themuvarov** [paramaggarwal/react-dropzone#40]
Steps to reproduce:
1. Choose a file A from file system in dropzone
2. onDrop does fire, the file eventuanaly sent
3. Modify body of the file A
4. Choose the same file
5. onDrop does not fire since it mapped to onChange form's event

Could fix if by adding the following line to onClick function.

React.findDOMNode(this.refs.fileInput).value = null;

**Comment by paramaggarwal** [comment]
We are using the HTML `onDrop` attribute on the `div` tag. If that's the default behaviour, then so be it. I don't see a reason to modify default behaviour here.

**Comment by themuvarov** [comment]
it was eventually fixed here https://github.com/paramaggarwal/react-dropzone/commit/8bcf347f8f1b5dd6c8ad2498b978772e3ff351dc

**Comment by mcmillhj-wta** [comment]
I am still experiencing this in 6.0.2 after https://github.com/react-dropzone/react-dropzone/commit/8bcf347f8f1b5dd6c8ad2498b978772e3ff351dc
